### PR TITLE
Automate signing

### PR DESCRIPTION
**Pull request by n8henrie**
Making a PR to trigger a CI build so we can see if the signing setup is working.

### CODE REVIEW

**Comment by pjrobertson** [comment]
@n8henrie  - does this need to stay open? Did the code-signing work as expected?

Next steps?

**Comment by n8henrie** [comment]
There's more discussion in the associated issue: https://github.com/quicksilver/Quicksilver/issues/2576

Not ready yet: <https://github.com/quicksilver/Quicksilver/runs/5046062463>

```
 codesign --verify --deep --strict --verbose=1 Quicksilver.app
Quicksilver.app: valid on disk
Quicksilver.app: satisfies its Designated Requirement
+ spctl --assess --verbose --type open --type exec ./Quicksilver.app
./Quicksilver.app: rejected
+ true
+ spctl --assess --verbose --type open --context context:primary-signature 'Quicksilver 1.6.1.dmg'
Quicksilver 1.6.1.dmg: rejected
```

Using the artifact from <https://github.com/quicksilver/Quicksilver/actions/runs/1787301564>:

Trying to open the DMG:

Screen Shot 2022-02-03 at 08 49 01

Right click -> Open -> double click `Quicksilver.app`

Screen Shot 2022-02-03 at 08 49 32

Right click `Quicksilver.app` and open and it runs as expected.

So the developer certficate still hasn't made `spctl` happy.

> Next steps?

Tinkering with `spctl` locally to see if we can get both of these happy:

- `spctl --assess --verbose --type open --type exec ./Quicksilver.app`
- `spctl --assess --verbose --type open --context context:primary-signature 'Quicksilver 1.6.1.dmg'`

I hadn't been able to get them to both work, and I had assumed it was because I don't have a valid developer certificate, so @skurfer was kind enought to put his into GitHub secrets; I'd hoped the GA would "just work" but clearly not.

So next step is to resolve the seeming discrepancy between the results of these two commands:

```
 codesign --verify --deep --strict --verbose=1 Quicksilver.app
Quicksilver.app: valid on disk
Quicksilver.app: satisfies its Designated Requirement
+ spctl --assess --verbose --type open --type exec ./Quicksilver.app
./Quicksilver.app: rejected
```

**Comment by pjrobertson** [comment]
Great, thanks for the update. Could it be that the plugins aren't getting signed? Just a thought.

When you're working on this, can you also add one line to qsrelease:

`xcodebuild test -project Quicksilver/Quicksilver.xcodeproj -scheme "Quicksilver Distribution" -destination 'platform=OS X,arch=x86_64' | xcpretty && exit ${PIPESTATUS[0]}`

So that we can also run tests at the same time, as mentioned in #2600. Thanks!

**Comment by n8henrie** [comment]
Continuing at https://github.com/quicksilver/Quicksilver/pull/2647

**Pull request closed without merging**
