### PR TITLE
An assortment of 4020 bugfixes

### PR DESCRIPTION
**Pull request by tiennou**
I'm currently working through the crashers for 4020.

For now, there's only one (I'm still massaging my crashreport wrangling machinery 😉).

- 324 reports currently, with 171 "different" crash locations.
- top crash (which is the only fix for now) has 100 occurrences
- second is `*** Collection <__NSDictionaryM: 0x608000047770> was mutated while being enumerated.` with 32.

Note that it's likely I'll continue bashing on this.

### CODE REVIEW

**Comment by tiennou** [comment]
Note, there are *not* 4020 bugfixes in here 😜.

**Comment by skurfer** [comment]
> Note that it's likely I'll continue bashing on this.

So don’t merge yet?

**Comment by tiennou** [comment]
Yep, I'll try to pinpoint a few others of those 171 crashes.

**Comment by tiennou** [comment]
I think that's all the "obvious" ones for now. Most of those are merely safety-checks-or-bail though...

**Comment by skurfer** [comment]
Great! I’ll take a look soonish.

**Comment by skurfer** [comment]
Are you looking at #2379 as part of this? If not, I can. (Or did you already find it and fix it with 02302509e1d8619df2eba1e5c57751df7afd08fd?)

**Comment by tiennou** [comment]
Heh, I think I saw a crashlog like that, but I didn't take the time to investigate. Now that I'm checking those `NSRunInformationalAlertPanel` calls, there aren't that many of them. And I have the feeling I rewrote those twice already 😉 (there's a version in the async-update-check branch, and I seem to remember redoing it after the QSAlertManager update landed but can't find the branch anymore).

**Pull request merged**
