### PR TITLE
Switch to Obj-c html parser (away from beautifulsoup and python)

### LINKED ISSUE #2728: [Bug]: Web Searches catalog empty
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Continuing from https://groups.google.com/g/blacktree-quicksilver/c/SAiNvKCukT8

It seems the Web Searches catalog is empty. When clicking 'Rescan resource' it seems to complete the scan without finding results:

Screen Shot 2022-04-10 at 08 37 39

### Steps to reproduce

1. Enter 'hello' via dot mode
2. Select the 'Find with…' action
3. [there are no options here]

### Expected behavior

The options from https://qs0.qsapp.com/plugin-data/web-search-list.php?type=simple should be visible.

### MacOS Version

macOS 10.14

### Quicksilver Version

2.0.3 (4031)

### Crash Logs or Spindump

_No response_

### Screenshots

_No response_

### Additional info

Based on the thread, I wonder if it's a command-line tools issue as I recently removed Xcode from my system. But I'm not clear if it's asking for permission.

### PR DESCRIPTION
**Pull request by pjrobertson**
Should fix #2728

The overheads of calling a python script and `import bs4` is also a bit OTT.

I've also tried to improve link parsing in general for the modern day web (data:image images, accessibility, buttons etc.) A nice modern update to `QSUURLParser.py` :)

### CODE REVIEW

**Comment by n8henrie** [comment]
> The overheads of calling a python script and import bs4 is also a bit OTT.

No doubt, though I bet the network request dwarfs the python in terms of time cost. At least with my rural internet!

**Comment by pjrobertson** [comment]
> No doubt, though I bet the network request dwarfs the python in terms of time cost. At least with my rural internet!

Tell me about it :P

-----

I've just snuck one sneaky commit in here (as I like to do, :D) which I noticed whilst debugging this  - the Result window no longer 'bumps' if you try and → into something that you can't. See commit [3ea99f4](https://github.com/quicksilver/Quicksilver/pull/2729/commits/3ea99f41354f9d35061d5670372bcc2a3cdd4fef)

Is this a problem for @skurfer @n8henrie on macOS 11/12? When did this stop working? I almost forgot this was a thing:

https://user-images.githubusercontent.com/150431/163074776-b3fa8f54-651f-4f05-bbe6-4a7e655b91e4.mov

**Comment by n8henrie** [comment]
Working well for me.

**Comment by pjrobertson** [comment]
Thanks for the update. If you think it's good to go, please merge. The consensus in #2728 is that this also fixes the issue for them.

**Pull request merged**
