### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by pjrobertson**
Does what it says on the tin. I'm still on macOS 10.14 with Xcode 11.2.1. These changes should be forwards compatible, and just keeps everything in line.

Please test out building with this branch on your system (macOS 11+). If no issues then it can be merged.

### CODE REVIEW

**Comment by pjrobertson** [comment]
Only thing that was tripping me up was the codesigning. I disabled it for debug builds using [this](https://stackoverflow.com/questions/31039513/how-can-i-skip-code-signing-for-development-builds-in-xcode)

Latest commit

**Comment by n8henrie** [comment]
Builds and runs for me, M1 Mac 12.2, XCode 13.2.1.

Good catch on `/usr/bin/python3` not existing on earlier Macs.

What's all the `importlib_metadata` business about in https://github.com/quicksilver/Quicksilver/pull/2591/commits/5c4a5d9742477f0036898a1fe6c296dceb2eba2e? What version of python3 are you using? Had been working fine on 3.9 and 3.10 for me...

**Comment by skurfer** [comment]
> What's all the `importlib_metadata` business about in 5c4a5d9?

I notice when building the plug-ins that `bltrversion` fails inside Xcode due to some `importlib` error. Maybe it’s to fix that? I’ll give this branch a test.

**Comment by pjrobertson** [comment]
> What's all the `importlib_metadata` business about in [5c4a5d9](https://github.com/quicksilver/Quicksilver/commit/5c4a5d9742477f0036898a1fe6c296dceb2eba2e)? What version of python3 are you using? Had been working fine on 3.9 and 3.10 for me...

Yeah, build was failing for me, saying unable to import `importlib_metadata`. Had to do a `pip install --target=. importlib_metadata` to get it working.

**Comment by pjrobertson** [comment]
Let me know if this is good to merge. Otherwise I can't build/work on anything else on QS

**Comment by pjrobertson** [comment]
Thanks! 💨 💨

**Pull request merged**
