### PR TITLE
Rework QSTask.

### LINKED ISSUE #1040: Task viewer pops up continually
On approximately a 10sec cycle. Version is B69, I'm running OSX 10.6.8.

### PR DESCRIPTION
**Pull request by tiennou**
This supersedes #1603 and #1265.

Major surgery on QSTask, this makes QSTask a *real* model-only object, kills the deadlock issues between `QSTaskController` and `QSTaskViewer` and fixes the auto-show/hide behavior once and for all (at least it seems to behave right, now ;-)) :

- It will show if there's a new task and the prefs says it (it was).
- It won't show if during the time the task was created and the time the viewer reacts the task is done. This should fix #1040, and stop me wanting to bash it each time I open a new tab.
- It won't try to auto-close the window if you open it manually and a task finishes (this fixes a never reported issue ;-)).

Known issues/discussion:

- The *first* time it opens (set it to automatically open, quit and restart so you get the catalog startup scan), the view is messed up because it extends all the way to the right, which looks weird.
- I've setup minimal code to correctly to handle subtasks, but there's no viewer suppport, and I'm not sure it's worth it. It was *mostly* present, but the only thing I can think that would use that is the catalog scanning, and maybe the update system.
- I'm tempted to push up the `HIDE_DELAY` by a few millisec, so you can see the task completed. Right now it just closes before you can even see the task has ended (which looks the same to the user, but could be nicer).
- I've killed the `target`/`action` mechanism it had for task cancellation, instead relying on a `cancelBlock`.
- Documentation. I really want to do this one, but I need some more time.
- This *could* break plugins that used tasks (there was a `-(QSObject *)result` method I've killed, plus the effects of the major surgery). But I don't think that many plugins did that, and I think the API as it is is sufficient for "general user information". But if you find I broke some plugin, I'll happily revise and provide at least a *private* runtime equivalent.
- Maybe the preferences settings should be also specified in the Extras pref pane ? I think it's pretty hidden atm, IIRC by default it won't autoshow, and you can't change those settings unless you open it first and fiddle with the gear menu. #119 talks about that a little.

All in all, eyes are welcome so I'm breaking anything, and if you stop a thing I didn't point out in the list above, the

### CODE REVIEW

**Comment by tiennou** [comment]
Rebased ! I've tried to fix the visual glitches but somewhat failed, the Delayed startup still bleeds through. That said, that Delayed startup thing is bound to disappear sometime in the Near Future™, so maybe it's reasonable to merge that so we can kiss goodbye to our deadlocks ?

Just noticed the `showProgress` thing. I'll fix that.

**Comment by skurfer** [comment]
I’m pretty sure 823c06a7da3dc01f18803edb9543b5d0cfbb23ec explains a crash I’ve seen several times (when using this branch). Have you run into this @tiennou? If you can’t reproduce, I’ll try to catch it in the debugger. (It always seems to happen in the background, so I can’t reproduce it at will.)

```
Crashed Thread:        6  Dispatch queue: com.apple.root.utility-qos

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000248c0d31bec0

VM Regions Near 0x248c0d31bec0:
    Memory Tag 250         0000000118752000-0000000118b52000 [ 4096K] r--/r-- SM=COW  
--> 
    MALLOC_NANO            0000600000000000-0000600000400000 [ 4096K] rw-/rwx SM=COW  

Application Specific Information:
objc_msgSend() selector name: retain

...

Thread 6 Crashed:: Dispatch queue: com.apple.root.utility-qos
0   libobjc.A.dylib               	0x00007fff8518f0dd objc_msgSend + 29
1   com.apple.Foundation          	0x00007fff8629d9ff NSKeyValueWillChange + 465
2   com.apple.Foundation          	0x00007fff86261801 -[NSObject(NSKeyValueObserverNotification) willChangeValueForKey:] + 216
3   com.apple.Foundation          	0x00007fff863055be _NSSetDoubleValueAndNotify + 235
4   com.blacktree.QSCore          	0x000000010539e40c __42-[QSLibrarian scanCatalogIgnoringIndexes:]_block_invoke + 473
5   libdispatch.dylib             	0x00007fff88421323 _dispatch_call_block_and_release + 12
6   libdispatch.dylib             	0x00007fff8841cc13 _dispatch_client_callout + 8
7   libdispatch.dylib             	0x00007fff8841f88f _dispatch_root_queue_drain + 935
8   libdispatch.dylib             	0x00007fff8842dfe4 _dispatch_worker_thread3 + 91
9   libsystem_pthread.dylib       	0x00007fff8b8a6a9d _pthread_wqthread + 729
10  libsystem_pthread.dylib       	0x00007fff8b8a43dd start_wqthread + 13
```

**Comment by tiennou** [comment]
Another one
```
Crashed Thread:        13  Dispatch queue: com.apple.root.utility-qos

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000018dd1d07bec0

VM Regions Near 0x18dd1d07bec0:
    WebKit Malloc          00000001193b3000-00000001193b4000 [    4K] ---/rwx SM=NUL  
--> 
    JS JIT generated code  0000365e7a400000-0000365e7a401000 [    4K] ---/rwx SM=NUL  

Application Specific Information:
objc_msgSend() selector name: retain

Thread 0:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x00007fff8c6b6d80 __CFStrHashEightBit2 + 0
1   com.apple.CoreFoundation      	0x00007fff8c6a98a7 -[NSStringROMKeySet_MacOSX indexForCString:length:key:] + 71
2   com.apple.CoreFoundation      	0x00007fff8c588266 __CFStringCreateImmutableFunnel3 + 2438
3   com.apple.CoreFoundation      	0x00007fff8c5a0dcc CFStringCreateWithSubstring + 460
4   com.apple.CoreFoundation      	0x00007fff8c628c99 -[__NSCFString _newSubstringWithRange:zone:] + 25
5   com.apple.Foundation          	0x00007fff8e5fc8ef -[NSObject(NSKeyValueCoding) valueForKeyPath:] + 226
6   com.apple.AppKit              	0x00007fff87ca9c46 -[NSBinder valueForBinding:resolveMarkersToPlaceholders:] + 164
7   com.apple.AppKit              	0x00007fff87d5f5ed -[NSProgressIndicatorBinder _updateObject:observedController:observedKeyPath:context:] + 101
8   com.apple.AppKit              	0x00007fff87d5f56e -[NSViewStateBinder _observeValueForKeyPath:ofObject:context:] + 126
9   com.apple.AppKit              	0x00007fff87ca1711 -[NSObject(NSKeyValueBindingCreation) bind:toObject:withKeyPath:options:] + 758
10  com.apple.AppKit              	0x00007fff87b640b6 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1065
11  com.apple.AppKit              	0x00007fff87d3ea0e -[NSNib _instantiateNibWithExternalNameTable:options:] + 677
12  com.apple.AppKit              	0x00007fff87d3e65e -[NSNib _instantiateWithOwner:options:topLevelObjects:] + 143
13  com.apple.AppKit              	0x00007fff87d3d957 -[NSViewController loadView] + 272
14  com.apple.AppKit              	0x00007fff87cbcf03 -[NSViewController _loadViewIfRequired] + 75
15  com.apple.AppKit              	0x00007fff87cbce6d -[NSViewController view] + 30
16  com.blacktree.Quicksilver     	0x000000010b3e2f01 __30-[QSTaskViewer updateTaskView]_block_invoke + 497 (QSTaskViewer.m:188)
17  libdispatch.dylib             	0x00007fff8babe323 _dispatch_call_block_and_release + 12
18  libdispatch.dylib             	0x00007fff8bab9c13 _dispatch_client_callout + 8
19  libdispatch.dylib             	0x00007fff8bac5cbf _dispatch_main_queue_callback_4CF + 861
20  com.apple.CoreFoundation      	0x00007fff8c63a3f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
21  com.apple.CoreFoundation      	0x00007fff8c5f568f __CFRunLoopRun + 2159
22  com.apple.CoreFoundation      	0x00007fff8c5f4bd8 CFRunLoopRunSpecific + 296
23  com.apple.HIToolbox           	0x00007fff8d77156f RunCurrentEventLoopInMode + 235
24  com.apple.HIToolbox           	0x00007fff8d7712ea ReceiveNextEventCommon + 431
25  com.apple.HIToolbox           	0x00007fff8d77112b _BlockUntilNextEventMatchingListInModeWithFilter + 71
26  com.apple.AppKit              	0x00007fff87bc99bb _DPSNextEvent + 978
27  com.apple.AppKit              	0x00007fff87bc8f68 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
28  com.apple.AppKit              	0x00007fff87bbebf3 -[NSApplication run] + 594
29  com.apple.AppKit              	0x00007fff87b3b354 NSApplicationMain + 1832
30  com.blacktree.Quicksilver     	0x000000010b3ef606 main + 198 (main.m:21)
31  libdyld.dylib                 	0x00007fff8f8145c9 start + 1
```

**Comment by tiennou** [comment]
Just rebased that, I finally got rid of the lingering task views. I'll keep running this one for a few days to make sure the crash is also gone.

Note that I've tweaked the behavior of `QSDockingWindow` because of craziness (7719943e1b6c82641b8cb4a260755221d7580628, e6162e95a19fbbb3aae80b53dd057bc718c03c5f). Now the task viewer remembers its on-screen location and you don't have to shove down lots of `setAutoSavedFrameWhatever:` down AppKit's throat ;-). I tested the Clipboard & Shelf windows but didn't seem to bother, so they were working around the issue already.

**Comment by tiennou** [comment]
Bug: it messes up the focus in Spaces. Also has a tendency to not hide itself sometimes.

**Comment by skurfer** [comment]
OK, I’m running with this once again. I know I’ve looked over the code like 3 times, so I’ll just test for real-world functionality.

If it looks good, I’ll also update the NIB deployment targets (unless you want to add that here) and I’ll finally be able to work on adding “run after delay” and “run at time” commands to the task viewer. 😃

**Comment by skurfer** [comment]
Three years later… Never give up hope!

The change log for this might take the rest of the day. :hurtrealbad:

**Comment by skurfer** [comment]
If I missed anything in 8636c0e4ad4c579deeb323ea7b535ed4771dad84, feel free to push change log updates straight to `master`.

**Comment by tiennou** [comment]
I think that covers it all.

**Comment by pjrobertson** [comment]
wow, awesome work guys!

**Pull request merged**
