### PR TITLE
Start migration to python3

### PR DESCRIPTION
**Pull request by n8henrie**

### CODE REVIEW

**Comment by n8henrie** [comment]
Fixes #2571

**Comment by skurfer** [comment]
OK, I hate the idea of complaining when someone is helping out, so I want to be clear that I appreciate you spending time on this.

Now, for my _actual_ first thought when I looked at this: Ugh. Looks like Black has ruined a couple more perfectly readable scripts. If you could convince your editor not to let Black take a dump in these files I’d appreciate it (but honestly, I’m not going to refuse the PR over it). 😏

**Comment by n8henrie** [comment]
¯\\_(ツ)_/¯ Thanks for your honesty. I've gotten used to it (especially after working with gofmt and rustfmt); I value the consistency and find the readability usually better than when others do their own thing. (FWIW, the majority of the 65 files changed were never opened in my editor, black is *ubiquitous* at this point, especially as it's officially under the umbrella of the PSF now.)

Are there certain changes you're particularly turned off by? Double quotes? I'll see if I can configure it.

**Comment by skurfer** [comment]
> FWIW, the majority of the 65 files changed were never opened in my editor

Oh, I know. I don’t care about those and they aren’t worth reformatting since we’ll just replace them again at some point. I’m just referring to the two scripts that we control within the project.

> Are there certain changes you're particularly turned off by? Double quotes?

Yes, mainly the double quotes. Single quotes are easier to read, easier to write, and they match the representation you’ll see in the Python REPL.

> I'll see if I can configure it.

If you’re using Black, you can’t and they’re very proud of it.

**Comment by n8henrie** [comment]
> Single quotes are easier to read, easier to write

I consider the extra effort of pressing `Shift` to be offset by not having to escape apostrophes in strings, and mentally more consistent with Go, Rust, and Swift. But it seems like you have a well-formed opinion here so I'm happy to play ball :) Thankfully a `%s/"/'/g` hopefully did the trick.

> and they match the representation you’ll see in the Python REPL.

That's a good point that I hadn't considered.

> If you’re using Black, you can’t

`skip-string-normalization = true` seems to be a reasonable workaround. I've added to a minimal config file so future contributors won't run into the same issue.

I still need to go through and make sure these are working in XCode, just wanted to get the ball rolling.

**Comment by n8henrie** [comment]
Fixed one more python script in preflight.

Looks like the changelogs are being generated without issue.

**Comment by skurfer** [comment]
OK, I’ll try to give this a look soon.

**Comment by skurfer** [comment]
Oh, I’ll look at this now since I see it’s holding your `master` branch hostage. Feel free to just set `origin` to the main repo and create your branches for PRs there going forward.

**Comment by skurfer** [comment]
Hmm. I assume you don’t see this?

~~~
Traceback (most recent call last):
  File "/tmp/QS/build/Debug/Quicksilver.app/Contents/PlugIns/Core Support.qsplugin/Contents/Resources/QSURLExtractor.py", line 18, in <module>
    from bs4 import BeautifulSoup
  File "/private/tmp/QS/build/Debug/Quicksilver.app/Contents/PlugIns/Core Support.qsplugin/Contents/Resources/bs4/__init__.py", line 36, in <module>
    raise ImportError('You are trying to use a Python 3-specific version of Beautiful Soup under Python 2. This will not work. The final version of Beautiful Soup to support Python 2 was 4.9.3.')
ImportError: You are trying to use a Python 3-specific version of Beautiful Soup under Python 2. This will not work. The final version of Beautiful Soup to support Python 2 was 4.9.3.
~~~

I know `/usr/bin/env python3` gives me something reasonable in a terminal. I’m trying to think of a way to see what it refers to in Quicksilver’s execution context. I don’t see how it could result in a Python 2 executable in any case though.

**Comment by n8henrie** [comment]
I have not seen that.

I did have to change a path in XCode (it wasn't respecting the shebang and
had a hard-coded `python2`), but I thought I included that change in the
PR. Will double check soon.

Are you seeing this at build time, startup, or during usage?

**Comment by skurfer** [comment]
I see it after I build and try to use the HTML link parser.

See the last paragraph in my previous comment for what I did. I’m wondering if you can reproduce it. If not, it must be something on my system.

**Comment by n8henrie** [comment]
> See the last paragraph

Sorry, was going from email which didn't register the edit.

> then tab back to the first pane and hit →

Yes, I see the same error. After ~13 years of continuous, daily, heavy use, with a number of [blog posts dedicated to QS][0] over that time frame, having evangelized it to anyone that will listen as my most-critical MacOS app... I had actually never used / didn't know about this functionality as far as I can recall. And I'm sure I will use it now -- QS is just such a deep rabbit hole.

[As an aside...](https://github.com/quicksilver/Quicksilver/issues/2584)

So [here's the issue][1]. Fixing the path still give some errors with regards to the path and soupsieve (which is needed due to an updated bs4) -- should be an easy fix.

I think hardcoding `/usr/bin/python3` would be expected to break compatibility with prior MacOS  versions that didn't ship with Python3 (was Big Sur the first?). ~~Perhaps just `python3`?~~ That doesn't work, doesn't do a `PATH` lookup because it's not running in a shell I guess, but using `/usr/bin/env` seems to work (since it is executable and has an appropriate shebang). This hopefully should mean pre-Big Sur users can use an e.g. homebrew-installed python3.

Also looks like much of the utilized NSTask API is deprecated. This might be a good candidate for me to [convert to Swift](https://developer.apple.com/documentation/foundation/process) as some point.

[0]: https://n8henrie.com/tags/#Quicksilver-ref
[1]: https://github.com/quicksilver/Quicksilver/blob/40f0f59c39797c251dfbd44563586663b6812ccc/Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSHTMLLinkParser.m#L51

**Comment by n8henrie** [comment]
Seems to be working with these.

**Comment by n8henrie** [comment]
Also, I don't see any other user-facing hardcoded python paths (just for one of the build phases which should only be run on dev machines AFAICT), so I think if this works for you it should be ready for merge.

**Comment by skurfer** [comment]
I just ran across something that might be related.

https://indiestack.com/2021/11/xcodes-environmental-pollution/

I can’t remember now, but I think I might have been running a Debug build from Xcode. Still, that wouldn’t explain why it’s running Python 2.

**Comment by n8henrie** [comment]
Did you try again since https://github.com/n8henrie/Quicksilver/commit/ebcd08e53e044ffe146f280203e68e9d74174b69? I was able to reproduce your error and think this fixed it.

**Comment by n8henrie** [comment]
🤦‍♂️ Sorry, I pushed those last changes to the n8henrie/n8henrie branch instead of n8henrie/master. Try again, the python2 issue should hopefully be gone.

Again, once these are merged I'll just branch from Quicksilver and set it up as my default remote.

**Pull request merged**
