### PR TITLE
Apply XCode recommended settings

### PR DESCRIPTION
**Pull request by n8henrie**
Only required 1 code change -- `extern` for `lastModifier`.

### CODE REVIEW

**Comment by pjrobertson** [comment]
Any way to make the .plist changes manually? Xcode loves to mess up the ordering of plists if you change just a single value (looks like you only changed CFBundleIdentifier?). That makes it more difficult track changes in history.

Albeit, if it's not easy - this isn't that much of a deal. It's only plists, not code

**Comment by pjrobertson** [comment]
@n8henrie - never mind about making the changes manually. Let's just get this merged. But there's a conflict now. Can you re-make the changes and then force-push? Then we can get it merged.

Thanks

**Comment by n8henrie** [comment]
Fixed a few conflicts and rebased

**Comment by n8henrie** [comment]
> Any way to make the .plist changes manually?

I bet there's a plist prettifier somewhere that would make these diffs better.

**Comment by pjrobertson** [comment]
Looks good

**Pull request merged**
