### PR TITLE
Add GHA badge to README

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by n8henrie** [comment]
I don't think using a badge for the `release` action makes sense, this is just cutting a release for new tags.

Using a badge in this way usually conveys some information to the reader (tests passing, test coverage percent, or just release version) -- this script currently is just creating a release.

**Comment by n8henrie** [comment]
I think it might be worthwhile to add a badge for the test suite, but I don't know how to run that yet.

Did you have other ideas regarding the purpose of adding this badge?

I also think that as soon as @skurfer gives the OK changing the links in the readme might be a worthwhile PR.

We should also look into whether or not we can sign releases with this github action -- hoping there may be some way to use the github environment secrets to do so.

**Comment by gliptak** [comment]
The approach might be considered here is to separate a build/test flow (validating PRs and indicating health of master branch and displaying badge) from the release flow (triggered when a v* tag is pushed onto master)

**Comment by skurfer** [comment]
> I also think that as soon as @skurfer gives the OK changing the links in the readme might be a worthwhile PR.

Changes to which links?

> We should also look into whether or not we can sign releases with this github action -- hoping there may be some way to use the github environment secrets to do so.

Has anyone gotten signing to work locally? I haven’t seen it work for years. I’ve tried a lot of things to fix it, but wasn’t able to figure out the problem.

**Comment by n8henrie** [comment]
> Changes to which links?

The official downloads can come from GitHub once this is working: <https://github.com/quicksilver/Quicksilver#where-to-download-quicksilver>

> Has anyone gotten signing to work locally? 

I assumed someone would need a (paid --$100 or so?) Apple developer signing certificate. I will probably get one in the next year but don't have one now. I can look for some kind of self-signed cert (which I think they generate for e.g. local iOS builds), but I assume it will give the same kinds of warning if I use it to sign an app that is distributed.

**Comment by gliptak** [comment]
https://github.com/quicksilver/Quicksilver/issues/2576#issuecomment-964647533

**Comment by skurfer** [comment]
> I assumed someone would need a (paid --$100 or so?) Apple developer signing certificate.

Correct. We (meaning me) have had one since Gatekeeper was introduced, but you will need one to try things out locally.

> I will probably get one in the next year but don't have one now.

If you end up getting one, let us know. @pjrobertson can reimburse you using donation money. We should probably still issue releases with mine for now so it will match prior releases.

**Comment by gliptak** [comment]
@skurfer if you configure the signing cert into GHA following above, I will open a PR to update GHA script

**Pull request closed without merging**
