### PR TITLE
Tweak default purples for a more modern look

### PR DESCRIPTION
**Pull request by pjrobertson**
This change makes QS's default theme colours more closely match the new logo styling/colour, and macOS's more 'vibrant' colour schemes of recent times.

Screenshot 2022-02-22 at 14 07 51

@vadimrob it would be great to get your thoughts as well, since you created the new icon :) If you have any suggestions for better default colour themes, then you can:
1. Change the colours from the QS 'Appearance' Preferences
2. Send me your Preferences file, located at `~/Library/Preferences/com.blacktree.Quicksilver.plist` (or if you don't want to share the entire thing, just the info in the 'Appearance XXX' keys.)

P.S. I hope my choice of text/command in the screenshot gets a chuckle :P

### CODE REVIEW

**Comment by skurfer** [comment]
Looks good to me, but Purple is my accent color. I’ll wait a bit to see if anyone wants to weigh in.

**Comment by n8henrie** [comment]
I'm partial to my default gray -- but no biggie as long as we can customize.

Speaking of which:

<https://github.com/quicksilver/Quicksilver/pull/2653/files#diff-8297b39085caca119ec29371c8cdf2b555dda8c58244e5dccae617ed8b73e258>

How did you [update QSDefaults.plist](https://github.com/quicksilver/Quicksilver/issues/2597)??

**Comment by pjrobertson** [comment]
We haven't heard from @vadimrob , so I suggest we merge this.

> How did you https://github.com/quicksilver/Quicksilver/issues/2597??

@n8henrie - I first set the colours using Quicksilver's interface, then went and found the `com.blacktree.Quicksilver.plist` file and copied the relevant data.

**Comment by n8henrie** [comment]
🤦‍♂️ should have thought of that. Thanks.

**Comment by hipunk** [comment]
Why change it from indigo to purple?

**Comment by pjrobertson** [comment]
> Why change it from indigo to purple?

Please see the original post: 

`This change makes QS's default theme colours more closely match the new logo styling/colour`

If you wish to change back to the old colours, you can tweak them in the appearance Quicksilver preferences
Screenshot 2022-04-17 at 17 03 47

**Comment by hipunk** [comment]
What color values were it? I want the original indigo, not some "purple".

**Comment by pjrobertson** [comment]
If you want to use he previous colour, open up terminal and paste the following:


```
defaults write com.blacktree.Quicksilver QSAppearance1B "<040b7479 70656473 74726561 6d8103e8 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016301 84046666 6666833e 07b43683 3dcbf447 833e4a52 94833f4c cccd86>"
defaults write com.blacktree.Quicksilver QSAppearance1T "<040b7479 70656473 74726561 6d8103e8 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016306 84034040 40848484 084e5353 7472696e 67019484 012b0653 79737465 6d868496 9821616c 7465726e 61746553 656c6563 74656443 6f6e7472 6f6c5465 7874436f 6c6f7286 84939503 84026666 01018686>"
defaults write com.blacktree.Quicksilver QSAppearance2A "<040b7479 70656473 74726561 6d8103e8 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016306 84034040 40848484 084e5353 7472696e 67019484 012b0653 79737465 6d868496 981b7365 6c656374 65645465 78744261 636b6772 6f756e64 436f6c6f 72868493 95038402 6666833f 2aaaab01 8686>"
defaults write com.blacktree.Quicksilver QSAppearance2B "<040b7479 70656473 74726561 6d8103e8 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016306 84034040 40848484 084e5353 7472696e 67019484 012b0653 79737465 6d868496 9815636f 6e74726f 6c486967 686c6967 6874436f 6c6f7286 84939503 84026666 01018686>"
defaults write com.blacktree.Quicksilver QSAppearance2T "<040b7479 70656473 74726561 6d8103e8 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016306 84034040 40848484 084e5353 7472696e 67019484 012b0653 79737465 6d868496 98147769 6e646f77 4672616d 65546578 74436f6c 6f728684 93950384 02666601 018686>"
defaults write com.blacktree.Quicksilver QSAppearance3A "<040b7479 70656473 74726561 6d8103e8 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016306 84034040 40848484 084e5353 7472696e 67019484 012b0653 79737465 6d868496 981b7365 6c656374 65645465 78744261 636b6772 6f756e64 436f6c6f 72868493 95038402 6666833f 2aaaab01 8686>"
defaults write com.blacktree.Quicksilver QSAppearance3B "<040b7479 70656473 74726561 6d8103e8 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016306 84034040 40848484 084e5353 7472696e 67019484 012b0653 79737465 6d868496 98137465 78744261 636b6772 6f756e64 436f6c6f 72868493 95038402 66660101 8686>"
defaults write com.blacktree.Quicksilver QSAppearance3T "<040b7479 70656473 74726561 6d8103e8 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016306 84034040 40848484 084e5353 7472696e 67019484 012b0653 79737465 6d868496 98097465 7874436f 6c6f7286 84939503 84026666 00018686>"
```

**Pull request merged**
