### PR TITLE
Update Quicksilver.icns 2022

### PR DESCRIPTION
**Pull request by vadimrob**
new quicksilver icon 2022
what do you think?

qs
Screenshot 2022-02-03 at 12 18 48
2

### CODE REVIEW

**Comment by pjrobertson** [comment]
That was quick, great job @vadimrob ! It looks like you've switched back to the purple background / white foreground of the current icon, as opposed to the inverted colours of your original icon?

quicksilver 2x

Are you able to make one with inverted colours? Then we can compare the two and have a vote, to choose which is the preferred icon! I'm thinking something like this icon in your dock pic:
152326188-9cd9285b-f6b2-4645-b195-e594db3d6e96

Also, here's how the icon looks in the 'Quit Quicksilver' dialog. If you could post that for the inverted colours, that would be helpful.

Screenshot 2022-02-04 at 08 24 16

**Comment by vadimrob** [comment]
@pjrobertson Yes it was quick you caught me in a less busy moment of the day and I quickly whiped something up. Yes I reverted back to the origins and gave the overall icon more of the QS color, but a little modified a little punchier a combination of Electric Violet and Eminence color. I think it gives more impact and visual identity impact in the dock, because so few apps have that background color. 

But I will do the inverted version also just give me a few days to complete it to find some time.

Thanks!

**Comment by pjrobertson** [comment]
Perfect! Looking forward to seeing the inverted version :D

**Comment by skurfer** [comment]
There’s already a “squircle” icon on the `master` branch. See if it’s suitable before doing too much work here.

**Comment by pjrobertson** [comment]
Thanks for the heads up @skurfer  - I wasn't aware of [that updated one here](https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/Resources/Images/Quicksilver.icns)

I'd vote for continuing with @vadimrob's icon, as he's also given it a more modern feel. Just waiting to see the inverted colours then we can decide which one to go for.

**Comment by vadimrob** [comment]
Attached is the inverted version:
152451644-bf4128c0-5fe7-47e4-b196-9502679ca397 2
qsw

**Comment by pjrobertson** [comment]
Great, thanks! I think I like the normal one more. @vadimrob - what are your thoughts?

Let's have a vote!

React to this message with:

1. A rocket 🚀  for the purple background with white logo
2. A hooray 🎉  for the white background with purple logo

**Comment by pjrobertson** [comment]
Looks like the rocket has it! Voting will close in 12 hours, at 12:00pm (UTC). :D

**Comment by pjrobertson** [comment]
Votes are in, we're going with purple backround + white logo!

@vadimrob - can you also update the `Quicksilver@2x.icns` file [in the same folder](https://github.com/quicksilver/Quicksilver/tree/9d8caff6e76b8469aa9472f2db05935a3bcd2f7f/Quicksilver/Resources/Images) and re-push here.

Then we'll get it merged.

Thanks!

**Comment by vadimrob** [comment]
@pjrobertson Hello! I'm a little busy with selling my car Today, but I'll update the required files Tomorrow.

**Comment by pjrobertson** [comment]
👍  good luck selling your car!

**Comment by vadimrob** [comment]
> 

Thank you! I sold it thankfully without problems.

**Comment by pjrobertson** [comment]
This looks great, thanks once again! Congratulations on your first commit to Quicksilver, and also on selling the car 😄 

Looking forward to getting this into the next release.

If you feel up for it, many of Quicksilver's other icons in [this folder](https://github.com/quicksilver/Quicksilver/tree/master/Quicksilver/Resources/Images) could do with a touch up. But that's probably quite a challenge, and may take up a fair amount of time.

**Comment by vadimrob** [comment]
> 

Thank you! Glad I could contribute. I don't know about the rest of the graphics, kinda low on time these days, but when I have time and feel like it I surely could help :).

**Comment by lgarron** [comment]
Would it make sense to add more resolutions to the `.icns` files?

In https://github.com/quicksilver/Quicksilver/pull/2544 I put a lot of care into the dimensions to match Apple's guidelines/icons, and also to make sure that the horizontal short line at the bottom remains visible in Finder at 1x monitor resolution (right side of screenshot).

Screen Shot 2022-03-16 at 17 41 39

**Comment by pjrobertson** [comment]
You raise a good point, Lucas. I've noticed the icons look 'fuzzy' when really small:
Screenshot 2022-03-17 at 09 36 41

I wasn't quite sure how to go about fixing these. Would you be able to add in the missing icon sizes? I'm not sure if that's possible since you don't have the original file from @vadimrob  - or maybe you can remake them using the same colour theme?

Thanks!

**Comment by vadimrob** [comment]
[quicksilverxrt.afdesign.zip](https://github.com/quicksilver/Quicksilver/files/8281820/quicksilverxrt.afdesign.zip)
Hello, here is the Affinity Design editable file. Sadly I don't have the time to do further work for now. 

Thanks!

**Comment by pjrobertson** [comment]
Thanks for this @vadimrob - much appreciated, and stay safe.

**Pull request merged**
