### PR TITLE
update the results window to use AutoLayout

### PR DESCRIPTION
**Pull request by skurfer**
A redo of #1924 

I wanted to get it out the door before it was completely forgotten.

### CODE REVIEW

**Comment by pjrobertson** [comment]
So we're totally getting rid of the child results view? I like it :-)

I'm assuming you've been running with this for a while, and you've tested it on El Capitan? How about 10.9 Mavericks? It looks great for me on 10.10

**Comment by skurfer** [comment]
I can try on El Capitan. I seem to have ditched my Mavericks VM, but I can get @claytron to try it out.

**Comment by skurfer** [comment]
Looks good on El Capitan.

**Comment by pjrobertson** [comment]
I actually think I have a Mavericks VM. I can test it when I get hold of my
hard drive - it's in your car ;-)

**Comment by pjrobertson** [comment]
There are quite a few problems with AutoLayout. I looked into fixing it (mainly the resize button) but it was all a mess. Should we just stick with the old way and scrap AutoLayout (but still remove the child split view)?

**Pull request closed without merging**
