### PR TITLE
fix version string

### PR DESCRIPTION
**Pull request by n8henrie**
- Truncate the version info if a tag is checked out
- Use QS_INFO_VERSION for version string

### CODE REVIEW

**Comment by pjrobertson** [comment]
@n8henrie  - can you change this part back?

Screenshot 2022-04-08 at 07 58 56

See my commit yesterday: dcd754e0b51a090ca980e2888b4ef2e7feb7162e

**Comment by pjrobertson** [comment]
If this works, then let's merge this and get 2.0.3 out. I inadvertently broke the updater _again_... see #2715 -  we should really set up more unit tests :'(

**Comment by n8henrie** [comment]
https://github.com/quicksilver/Quicksilver/actions/runs/2112256934

**Comment by pjrobertson** [comment]
Great. Looks like this is building correctly. Can you confirm, and also that the plist is correct? If so, then feel free to merge and we can get 2.0.3 out

**Comment by n8henrie** [comment]
LGTM, though maybe I should cross-reference `"LSMinimumSystemVersion" => "10.14"` with another recent issue.

Screen Shot 2022-04-07 at 19 10 04

```console
$ plutil -p Info.plist
{
  "BuildMachineOSBuild" => "20G527"
  "CFBundleDevelopmentRegion" => "English"
  "CFBundleDocumentTypes" => [
    0 => {
      "CFBundleTypeExtensions" => [
        0 => "silver"
      ]
      "CFBundleTypeIconFile" => "silver"
      "CFBundleTypeName" => "Quicksilver Archive"
      "CFBundleTypeRole" => "Editor"
      "LSTypeIsPackage" => 0
    }
    1 => {
      "CFBundleTypeExtensions" => [
        0 => "qsshelf"
      ]
      "CFBundleTypeIconFile" => "qsshelf"
      "CFBundleTypeName" => "Quicksilver Shelf"
      "CFBundleTypeRole" => "Viewer"
      "LSTypeIsPackage" => 0
    }
    2 => {
      "CFBundleTypeExtensions" => [
        0 => "*"
      ]
      "CFBundleTypeName" => "Everything"
      "CFBundleTypeOSTypes" => [
        0 => "****"
        1 => "fold"
        2 => "disk"
      ]
      "CFBundleTypeRole" => "None"
      "LSTypeIsPackage" => 0
    }
    3 => {
      "CFBundleTypeExtensions" => [
        0 => "qsplugin"
      ]
      "CFBundleTypeIconFile" => "QSPlugIn"
      "CFBundleTypeName" => "Quicksilver Plugin"
      "CFBundleTypeRole" => "Editor"
      "LSTypeIsPackage" => 1
    }
    4 => {
      "CFBundleTypeExtensions" => [
        0 => "qscatalogentry"
      ]
      "CFBundleTypeName" => "Quicksilver Catalog Entries"
      "CFBundleTypeRole" => "Viewer"
      "LSTypeIsPackage" => 0
    }
    5 => {
      "CFBundleTypeExtensions" => [
        0 => "qspkg"
      ]
      "CFBundleTypeIconFile" => "qspkg"
      "CFBundleTypeName" => "Quicksilver Package"
      "CFBundleTypeRole" => "Viewer"
      "LSTypeIsPackage" => 0
    }
    6 => {
      "CFBundleTypeExtensions" => [
        0 => "qscommand"
      ]
      "CFBundleTypeIconFile" => "qscommand"
      "CFBundleTypeName" => "Quicksilver Command"
      "CFBundleTypeRole" => "Editor"
      "LSTypeIsPackage" => 0
      "NSPersistentStoreTypeKey" => "Binary"
    }
  ]
  "CFBundleExecutable" => "Quicksilver"
  "CFBundleHelpBookFolder" => "QSHelp"
  "CFBundleHelpBookName" => "Quicksilver Help"
  "CFBundleIconFile" => "Quicksilver"
  "CFBundleIdentifier" => "com.blacktree.Quicksilver"
  "CFBundleInfoDictionaryVersion" => "6.0"
  "CFBundleName" => "Quicksilver"
  "CFBundlePackageType" => "APPL"
  "CFBundleShortVersionString" => "2.0.2"
  "CFBundleSignature" => "daed"
  "CFBundleSupportedPlatforms" => [
    0 => "MacOSX"
  ]
  "CFBundleURLTypes" => [
    0 => {
      "CFBundleURLName" => "Quicksilver Installation URL"
      "CFBundleURLSchemes" => [
        0 => "qsinstall"
      ]
    }
    1 => {
      "CFBundleURLName" => "HTTP-POST Quicksilver Query"
      "CFBundleURLSchemes" => [
        0 => "qssp-http"
      ]
    }
    2 => {
      "CFBundleURLName" => "HTTP-GET Quicksilver Query"
      "CFBundleURLSchemes" => [
        0 => "qss-http"
      ]
    }
    3 => {
      "CFBundleURLName" => "Quicksilver"
      "CFBundleURLSchemes" => [
        0 => "qs"
      ]
    }
  ]
  "CFBundleVersion" => "4030"
  "DTCompiler" => "com.apple.compilers.llvm.clang.1_0"
  "DTPlatformBuild" => "13C100"
  "DTPlatformName" => "macosx"
  "DTPlatformVersion" => "12.1"
  "DTSDKBuild" => "21C46"
  "DTSDKName" => "macosx12.1"
  "DTXcode" => "1321"
  "DTXcodeBuild" => "13C100"
  "LSArchitecturePriority" => [
    0 => "arm64"
    1 => "x86_64"
  ]
  "LSHasLocalizedDisplayName" => 1
  "LSMinimumSystemVersion" => "10.14"
  "LSUIElement" => 1
  "NSAppleEventsUsageDescription" => "Quicksilver requires this access to run certain actions and update your catalog."
  "NSAppleScriptEnabled" => 1
  "NSAppTransportSecurity" => {
    "NSAllowsArbitraryLoads" => 1
  }
  "NSCalendarsUsageDescription" => "Create events directly from Quicksilver (only used when the 'Calendar' plugin is enabled)"
  "NSContactsUsageDescription" => "View, copy and paste information from your contacts in Quicksilver (only used when the 'Contacts' plugin is enabled)"
  "NSHumanReadableCopyright" => "Copyright © 2000-2008 Blacktree, Inc."
  "NSMainNibFile" => "MainMenu"
  "NSPrincipalClass" => "QSApp"
  "NSRemindersUsageDescription" => "Create reminders directly from Quicksilver (only used when the 'Calendar' plugin is enabled)"
  "NSServices" => [
    0 => {
      "NSKeyEquivalent" => {
        "default" => "⎋"
      }
      "NSMenuItem" => {
        "default" => "Send to Quicksilver"
      }
      "NSMessage" => "getSelection"
      "NSPortName" => "Quicksilver"
      "NSRequiredContext" => {
      }
      "NSSendFileTypes" => [
        0 => "public.data"
      ]
      "NSSendTypes" => [
        0 => "NSFilenamesPboardType"
        1 => "NSFileContentsPboardType"
        2 => "NSFontPboardType"
        3 => "NSColorPboardType"
        4 => "NSHTMLPboardType"
        5 => "NSPDFPboardType"
        6 => "NSPICTPboardType"
        7 => "NSPostScriptPboardType"
        8 => "NSRulerPboardType"
        9 => "NSRTFPboardType"
        10 => "NSRTFDPboardType"
        11 => "NSStringPboardType"
        12 => "NSTabularTextPboardType"
        13 => "NSTIFFPboardType"
        14 => "NSURLPboardType"
        15 => "NSVCardPboardType"
        16 => "NSFilesPromisePboardType"
      ]
      "NSTimeout" => "5000"
      "NSUserData" => "GetSelection"
    }
  ]
  "NSSupportsAutomaticGraphicsSwitching" => 1
  "QSReleaseStatus" => 0
  "UTExportedTypeDeclarations" => [
    0 => {
      "UTTypeConformsTo" => [
        0 => "com.apple.bom-compressed-cpio"
      ]
      "UTTypeDescription" => "Quicksilver PKG"
      "UTTypeIconFile" => "QSPkg.icns"
      "UTTypeIdentifier" => "com.blacktree.qspkg"
      "UTTypeTagSpecification" => {
        "public.filename-extension" => [
          0 => "qspkg"
        ]
      }
    }
    1 => {
      "UTTypeConformsTo" => [
        0 => "com.apple.bundle"
      ]
      "UTTypeDescription" => "Quicksilver Plugin"
      "UTTypeIconFile" => "QSPlugIn.icns"
      "UTTypeIdentifier" => "com.blacktree.qsplugin"
      "UTTypeTagSpecification" => {
        "public.filename-extension" => [
          0 => "qsplugin"
        ]
      }
    }
  ]
}
```

**Comment by n8henrie** [comment]
v2.0.3 pushed

**Comment by n8henrie** [comment]
> @n8henrie - looks like the DMG name is still wrong:

The DMG name (and version name as in the screenshot above) are both now derived from `QS_INFO_VERSION` (independent of the tag name). I should have updated that (somewhere?) before pushing, I'll delete the tag.

```
$ xcodebuild -destination "platform=macOS,arch=arm64" -configuration Release -scheme 'Quicksilver Distribution' -showBuildSettings 2>/dev/null | grep QS_INFO_VERSION
    QS_INFO_VERSION = 2.0.2
    QS_INFO_VERSION = 2.0.2
```

**Comment by n8henrie** [comment]
https://github.com/quicksilver/Quicksilver/actions/runs/2112540667

**Comment by pjrobertson** [comment]
Right. See Configuration/Developer.xcconfig

**Comment by pjrobertson** [comment]
Hold up, you also need to update `QS_BUNDLE_VERSION`

The Release Process could do with some improving. Right now it just says:

` Update the version number (ß6x) and build number (3xxx) in Developer.xcconfig `

**Comment by n8henrie** [comment]
Gah.

https://github.com/quicksilver/Quicksilver/releases/tag/v2.0.3

**Comment by n8henrie** [comment]
Download name and version number in Finder -> Info look good.

**Comment by pjrobertson** [comment]
That looks good :) The ß was from a time gone by. We switched away from that to regular naming conventions with v1.0 10 years ago.

We disabled bltrversion, because it was a pain to have it keep incrementing on every local build. But maybe now we have CI we can re-enable it for CI builds? Increment, commit, push back to master? @skurfer  - thoughts?

**Comment by pjrobertson** [comment]
@n8henrie - looks like the run is failing, and the bundle version is still wrong in the .dmg

https://github.com/quicksilver/Quicksilver/actions/runs/2112555372

**Comment by n8henrie** [comment]
Failed due to an identically named asset already existing. Deleted that and triggered a re-run, we'll see how that works.

As an aside, I'm also somewhat interested in adding a sha256 (or even just MD5) to the release assets. I know I've been surprised several times that GitHub doesn't automatically provide these!

**Comment by n8henrie** [comment]
2.0.3 looks good to me.

**Pull request merged**
