### PR TITLE
recent documents for El Capitan

### LINKED ISSUE #2079: El Capitan Public Beta: Drill from app to recent documents broken
Hi, normally if I select an app in the first pane then press ➡︎ I get to select recent documents. This is not working for me at the moment with 10.11 Beta (15A225f) and QS 4011. I think this was default behaviour before.

### PR DESCRIPTION
**Pull request by skurfer**
I sense we don’t have a lot of time, so hopefully one of you can look at this soon. :smile:

fixes #2079

### CODE REVIEW

**Comment by pjrobertson** [comment]
Sure thing I can look at it soon. Sorry for the flurry of comments :cry:

**Comment by tiennou** [comment]
FYI `$objects` key =>  NSCoder archive.

**Comment by skurfer** [comment]
> FYI `$objects` key => NSCoder archive.

Ah, OK. So how would I correctly read the values? Load the file as `NSData` instead and call `initWithCoder:`? How do you know which coder was used? Could it be private?

**Comment by tiennou** [comment]
I'd say `+[NSKeyedUnarchiver unarchiveObjectWithFile:]`. [Documentation](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSKeyedUnarchiver_Class/index.html#//apple_ref/occ/clm/NSKeyedUnarchiver/unarchiveObjectWithFile:)

But I have no idea what you'll get back from it ;-). It might just be a little more future-proof (future-private-API-proof-lolno :laughing:). At least it might be easier to work with...

**Comment by skurfer** [comment]
OK, have a look.

We get back `SFLListItem` objects, which I think is private, but I still trust this code more than what was there. Thanks!

**Comment by skurfer** [comment]
It’s checking for `nil` URLs now. Let me know if there’s anything else.

**Comment by pjrobertson** [comment]
No, that was all
I'm away from a computer... please merge :)
If need be we can get a release out for El Ca's release date

**Pull request merged**
