### PR TITLE
Use github actions to run unit tests

### LINKED ISSUE #1852: XCTest Unit Tests failing on Jenkins
Initially this was thought to be a UI problem, but I don't think it is.

It may well be a problem with XCTest in general (which I recommend we change to for all unit tests in the near future anyway).

Here's some useful links:
http://dev-blog.xoom.com/2014/02/15/migrating-ios-continuous-integration-builds-unit-tests-xcode-5/
https://issues.jenkins-ci.org/browse/JENKINS-19955?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel

I've just tried removing some of the possibly problematic code from the Unit Test I created, but Jenkins is still hanging: http://jenkins.henningj.com:8080/job/Quicksilver/77/console (sorry @HenningJ )

### PR DESCRIPTION
**Pull request by pjrobertson**
Fixes #1852

Hopefully this PR will trigger two GH actions - the existing one and the new unit tests.

### CODE REVIEW

**Comment by pjrobertson** [comment]
Hmm, can't get the test phase to build properly.

Perhaps instead @n8henrie - as you're working on fixing up qsrelease, can you also add this line after the existing build phase has been complete?

`xcodebuild test -project Quicksilver/Quicksilver.xcodeproj -scheme "Quicksilver Distribution" -destination 'platform=OS X,arch=x86_64' | xcpretty && exit ${PIPESTATUS[0]}`

I'll close this now

**Comment by n8henrie** [comment]
@pjrobertson 

It currently has this before the build phase, `|| true` because it's not passing. Is that adequate?

```
xcodebuild \
    -project Quicksilver/Quicksilver.xcodeproj \
    -destination "platform=macOS,arch=${CURRENT_ARCH}" \
    -scheme 'Quicksilver Distribution' \
    test || true
```

https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/Tools/qsrelease#L47

**Comment by pjrobertson** [comment]
That doesn't run the tests. To run the tests, it needs `xcodebuild test` - the `test` word in there.

This PR almost got things working, I'll re-open so you can see what the issues were

**Comment by pjrobertson** [comment]
Oh wait, I missed the `test` at the end of that command - so you are running the tests. In that case, just need to figure out the dependency problem.

**Comment by pjrobertson** [comment]
Closing in favour of #2632

**Pull request closed without merging**
