### PR TITLE
Update deployment target to 10.10

### PR DESCRIPTION
**Pull request by skurfer**
Since one line in the notification update requires 10.10, might as well make the leap.

The only questionable thing is the change to the return type for `macOSXSystemVersion`, but it’s unused from what I can see.

Also, I didn’t touch the NIBs that have already been updated in other pull requests.

### CODE REVIEW

**Comment by pjrobertson** [comment]
I'm good with this. One strange thing - builds seem to be failing right now. Any idea why? What got merged in that's breaking CI builds?

**Comment by tiennou** [comment]
Travis says the build was scheduled on a retired disk image (so builds against Xcode 7.3.1), then :
```
Failures:
  0) Compile XIB file /Users/travis/build/quicksilver/Quicksilver/Quicksilver/Nibs/QSPluginUpdater.xib
**snip**
/Users/travis/build/quicksilver/Quicksilver/Quicksilver/Nibs/QSPluginUpdater.xib: error: The document “(null)” requires Xcode 8.0 or later.
```

**Comment by tiennou** [comment]
`tenten` 😆

**Comment by skurfer** [comment]
I see the same thing on my 10.10 VM (now that I’ve had a chance to try it). I’ll do the NIB updates there (in Xcode 7.2.1) and try again.

**Pull request closed without merging**
