### PR TITLE
Add a "Latest Screenshot" proxy object. Implements #2749.

### PR DESCRIPTION
**Pull request by lgarron**
This is based on the "Latest Download" proxy object, which has an implementation that I've adapted and simplified.

### CODE REVIEW

**Comment by pjrobertson** [comment]
I love this idea. I have the same issues as you in #2749 - great idea and implementation! I've left a few code notes above :)

**Comment by n8henrie** [comment]
My implementation leaves a lot to be desired, but here is the script I've been using to accomplish this for the last several years: https://gist.github.com/n8henrie/7425598

I'm in favor of having it as a built-in proxy object, thanks for the contribution.

**Comment by lgarron** [comment]
> I love this idea. I have the same issues as you in #2749 - great idea and implementation! I've left a few code notes above :)

Thanks! The UI can be a bit finicky — mind making sure that your intended notes were posted? :-D

**Comment by pjrobertson** [comment]
See my 'pending' reviews above: 

https://github.com/quicksilver/Quicksilver/pull/2752/files/8234fe0737c561a90288b0bfb22324c2f970ee03#diff-146868b46e2845625322af2e3a9077137358a12e14f4d4039664bee55ecdf4ffR71
https://github.com/quicksilver/Quicksilver/pull/2752/files/8234fe0737c561a90288b0bfb22324c2f970ee03#diff-146868b46e2845625322af2e3a9077137358a12e14f4d4039664bee55ecdf4ffR67

**Comment by lgarron** [comment]
> See my 'pending' reviews above:

Unfortunately, I can't see those until you submit them! 😢
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request

**Comment by pjrobertson** [comment]
I'll fix up the other small issue I saw. Thanks for the contribution, this is a great addition!

**Comment by pjrobertson** [comment]
Sidenote: the Screen Capture plugin may well be another way to achieve what you want

**Comment by skurfer** [comment]
> Sidenote: the Screen Capture plugin may well be another way to achieve what you want

I might have argued that this proxy object should be in that plug-in instead of Core Support, but it’s not worth messing with at this point.

**Pull request merged**
