### PR TITLE
Allow specifying the configuration for qsrelease

### PR DESCRIPTION
**Pull request by n8henrie**
Fixes https://github.com/quicksilver/Quicksilver/issues/2868

### CODE REVIEW

**Comment by pjrobertson** [comment]
LGTM. One issue I have is that `CURRENT_ARCH=$(arch)` gives me `i386`. Apparently this is a quirk with `arch`(see [here](https://apple.stackexchange.com/questions/140651/why-does-arch-output-i386)) - I think what we actually want is `uname -m`. Can you confirm and make the change if necessary?

P.S. Right now, to get around this I define `CI` when I run `qsrelease` like this:

`CI="blahblahblah" ./qsrelease`

**Comment by n8henrie** [comment]
> One issue I have is that CURRENT_ARCH=$(arch) gives me i386

Interesting! https://superuser.com/a/835519/321164

> Right now, to get around this I define CI when I run qsrelease like this:

😆 Sorry about that.

PR soon.

**Comment by n8henrie** [comment]
Converted to a draft -- added some debug stuff to see what the values are in CI (which I will remove before ready to merge).

**Review by n8henrie — COMMENTED** [review]
I guess I can't turn it back from a draft into a PR without reviewing it.

**Comment by n8henrie** [comment]
@pjrobertson @skurfer would you guys mind pulling and building locally to make sure the `uname -m` change works okay locally? Seems like it's doing the right thing in CI.

**Comment by n8henrie** [comment]
Closing in favor or https://github.com/quicksilver/Quicksilver/pull/2871, which contains this and a bit more.

**Comment by pjrobertson** [comment]
OK. I was just about to review this :)

**Pull request closed without merging**
