### PR TITLE
Fix colours for dark mode

### LINKED ISSUE #2638: Preferences look ugly in Dark Mode
When using dark mode, the preferences look ugly, especially these white lines:
Screen Shot 2022-02-15 at 21 39 07

See more dark mode screenshots in #2537

### PR DESCRIPTION
**Pull request by pjrobertson**
Removes previous 'custom' colours (yellow/purple etc.) from Triggers/Catalog/Plugins views, but by not hard-coding colours, we can use the system's defaults

Fixes #2638

### CODE REVIEW

**Comment by pjrobertson** [comment]
Some screenshots (could still be improved, but this is much better than before).
Screenshot 2022-02-16 at 13 38 14
Screenshot 2022-02-16 at 13 38 17
Screenshot 2022-02-16 at 13 38 23

**Comment by n8henrie** [comment]
Looks great here too, thanks for sorting this out!

https://github.com/quicksilver/Quicksilver/issues/2537#issuecomment-1041139035

**Comment by pjrobertson** [comment]
@n8henrie @skurfer - there's one more view that I can't update. Xcode keeps crashing on me. I'm only on Xcode 11, maybe it was fixed in a later Xcode. Can you try the following:

1. Open up the `QSHelpersPrefPane.xib` file
2. Accept the warning:
Screenshot 2022-02-16 at 18 44 36
3. Click on the table, then in the sidebar drill down until you get to the 'table view' item (see left of pic below)
4. After clicking the table, go to the right sidebar and change 'Grid Color' to 'Separator Color'
5. Save, commit, then push back here.

Screenshot 2022-02-16 at 18 45 30

**Comment by skurfer** [comment]
> there's one more view that I can't update. Xcode keeps crashing on me.

That’s been happening since Xcode 8. I upgraded all the NIBs at one point, but had to skip that one. I even tried using the command-line `ibtool` on it, but no luck.

We talked about it in #2295. [This other comment](https://github.com/quicksilver/Quicksilver/pull/2153#issuecomment-155654502) makes it sound like I fixed it somehow, but obviously, I didn’t.

**Comment by pjrobertson** [comment]
OK, if that's the case I'll follow the instructions [here](https://stackoverflow.com/questions/39603792/xcode-8-crashes-when-opening-a-project-exc-crash-sigabrt-and-exc-corpse-notify/42186174#42186174)

The crash log for Xcode gives some explanation:

```
ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEInterfaceBuilder/IDEInterfaceBuilder-15505/InterfaceBuilderKit/Document/IBDocument.m:2557
Details:  An instance of NSWindowTemplate with object ID 5 did not archive its child (NSPopUpButtonCell) with an object of ID 144.
Edit log: (
    "Change Grid Color"
)
```

**Comment by pjrobertson** [comment]
@skurfer - I did see one mention that it was an issue with Mojave. If possible, can you please try opening and saving on your latest Xcode/macOs, just in case. If it's still no-go I'll follow the steps above

**Comment by skurfer** [comment]
Opening and saving in Xcode 13.2 on macOS 12.2.1 → Instant crash

**Comment by pjrobertson** [comment]
👍  for checking, thanks. 👎  for Xcode! I'll look into it.

**Comment by n8henrie** [comment]
My saga with the insta-crash on `QSHelpersPrefPane.xib` (and a few posts below): https://github.com/quicksilver/Quicksilver/issues/2537#issuecomment-1030245694

I couldn't get it figured out. Tried looking at the diffs made with the Xcode "auto-fix" on similar files to see if I could do it manually, but it didn't seem practical.

**Comment by skurfer** [comment]
Wait, just like I said in the linked comment, removing the two button cells at the bottom allows me to save it. Do they do anything? Trying to test now.

**Comment by pjrobertson** [comment]
Rob to the rescue! That's it, great catch. Those NSPopupCells were just 'floating' which probably isn't allowed and hence why Xcode was crashing.

I was able to open and delete them as well. Xib updated and pushed here. This PR should be good to go now.

**Pull request merged**
