### PR TITLE
Ndhotkey fixes

### LINKED ISSUE #2418: Delete key not displayed in trigger key shortcuts
Quicksilver 1.5.6 (4021) under macOS 10.13.2 (17C88).

Steps to reproduce:
1. Go to Triggers > Custom Triggers
2. Create a new trigger
3. Set the Shortcut for the trigger to _Cmd-option-delete_
4. Observe that the displayed shortcut is simply "⌥⌘"

The shortcut _does_ work as set, it simply isn't displayed correctly.

Other "invisible" keys (e.g. space, return) have visible representations.

### PR DESCRIPTION
**Pull request by pjrobertson**
Replaces #1147

Who'd have thought this would be so simple. Just needed to import the latest NDHotKey classes.

Try following the steps at #1134 to test. Looks like this also fixes #2418 as well:
Screenshot 2022-02-03 at 09 47 59

### CODE REVIEW

**Comment by pjrobertson** [comment]
Force-pushes just fixed some submodule checkout stuff that wasn't working properly in the GH actions. Nothing changed in the code.

(Note to self: a submodule's parent folder should be checked-in to git, so that the reference/link is there)

**Comment by timvisher** [comment]
This is even more exciting to me than the possibility of getting a native M1 build. ♪♪ ヽ(ˇ∀ˇ )ゞ

**Comment by skurfer** [comment]
Seems to fix displaying the higher-numbered function keys as well.

**Comment by pjrobertson** [comment]
10 years in the making, such a simple fix :)

Thanks Rob for merging

**Comment by timvisher** [comment]
woo myster men glitter

**Pull request merged**
