### PR TITLE
Make length of QSHistory editable

### PR DESCRIPTION
**Pull request by pjrobertson**
Nothing much here. I realised the QSHistory preset in the catalog (Catalog > Quicksilver > Recent Objects) is limited to 50. That's not enough for me.

I made it a hidden preferences to allow you to edit this value (ideally it'd be a setting in the Catalog UI but I don't have the time for this :(

### CODE REVIEW

**Comment by skurfer** [comment]
OK, but I say we get rid of `MAXHIST` entirely and set the default in `QSDefaults.plist`, since that’s the standard way we handle such things.

**Comment by tiennou** [comment]
And I say "add it to the Advanced prefs" 😉. IIRC it's just about a few lines in a plist (if it supports integer values).

**Comment by skurfer** [comment]
I did the things. 🆒

**Comment by pjrobertson** [comment]
Looks good. Can I merge a PR that I started? I say yes! :D

**Comment by skurfer** [comment]
Yup.

**Comment by skurfer** [comment]
Of course I just noticed this, but you can’t actually change the number in Extras. You can see what it is, though! 😁

**Comment by tiennou** [comment]
Gosh, I wonder whose fault it is 😁.

I was pretty sure it was working… Oh well, at least it's somewhat auto-documenting.

**Comment by pjrobertson** [comment]
😨 Ooops!

I think we should try and do away with the 'Extras' tab in the future anyway. It's not very self-explanatory, and some of the prefs should maybe even be deleted. Another job for another day :P

**Pull request merged**
