### PR TITLE
Update the white-on-purple icon to a version with more sizes.

### PR DESCRIPTION
**Pull request by lgarron**
For https://github.com/quicksilver/Quicksilver/issues/2685

This is an adaptation of the design from https://github.com/quicksilver/Quicksilver/pull/2595 with some of the tweaks from https://github.com/quicksilver/Quicksilver/pull/2544 to better match the macOS icon template sizes from Apple and make the icon look sharper at small resolutions. In particular, the `16x16(@1x)` icon contains a lot of manual adjustments:

Dark mode:
Screen Shot 2022-03-25 at 19 38 17

Light mode:
Screen Shot 2022-03-25 at 19 38 35

icon_16x16
icon_32x32
icon_64x64
icon_128x128
icon_256x256
icon_512x512
icon_512x512@2x

Quicksilver still has `.icns` files with an unusual spread of resolutions (old on the left); I've tried to keep it close (new on the right):
Screen Shot 2022-03-25 at 05 41 12
It would still be nice to update to a single icon in the future.

Happy to revise this if it's still not quite right.

### CODE REVIEW

**Comment by lgarron** [comment]
Looks like the `build / sign` CI job doesn't like my face. 🤷

**Comment by pjrobertson** [comment]
Thanks @lgarron - these look really good! No problems here :)

You don't need to worry about the build/sign failing. It fails for anybody who is not an owner of this repository. Perhaps the only thing I would ask is - can you add the original files (AI/PSD/afdesign) that you used to the repository, in the same folder. That way we always have them there as a record.

Thanks!

**Comment by lgarron** [comment]
> Perhaps the only thing I would ask is - can you add the original files (AI/PSD/afdesign) that you used to the repository, in the same folder. That way we always have them there as a record.

Unfortunately I'm not really about the situation with this. I accidentally ended up using a trial of the subscription version of Sketch (it is sneakily presented as a routine update from the last perpetual license version). I'll have to figure out a more sustainable format approach. :-/

**Comment by lgarron** [comment]
> > Perhaps the only thing I would ask is - can you add the original files (AI/PSD/afdesign) that you used to the repository, in the same folder. That way we always have them there as a record.
> 
> Unfortunately I'm not really about the situation with this. I accidentally ended up using a trial of the subscription version of Sketch (it is sneakily presented as a routine update from the last perpetual license version). Also, the file is 6.7MB, which I feel isn't really an appropriate weight. I'll have to figure out a more sustainable format approach. :-/

Here's a 4.9MB slightly pared down version, if you still want:
https://www.dropbox.com/s/7lemwwwu89vg9j2/Quicksilver%20Big%20Sur%20Inverted%20v0.8.4.1.sketch?dl=

**Comment by pjrobertson** [comment]
Great! I'll merge this and then add the sketch file to the repository as well :)

On behalf of the Quicksilver community - thanks!

**Comment by pjrobertson** [comment]
P.S. - note that I only meant for this file to be included in the QS repository for future needs, not in the app itself. So it doesn't really matter how big it is. It can just sit in the repository until it's needed again.

I've uploaded your 4.9MB version here: https://github.com/quicksilver/Quicksilver/commit/4e37a9caa67b042d77614c60712859da950faece

But please make a PR for the full 6.7MB if there are significant differences between the two versions.

**Comment by lgarron** [comment]
> But please make a PR for the full 6.7MB if there are significant differences between the two versions.

There are no differences that affect the final icons.

Adding the final file takes the checked-out files from 12.5MB to 17.2MB (and adds a few percent to the `.git` dir), which I think isn't a *great* use of bytes. If I'd have known this would be checked in, I would have found a way to generate these from something much lighter. But I'll certainly defer to you on whether to keep this in tree!

**Pull request merged**
