### PR TITLE
Debug uploading the debug artifact

### PR DESCRIPTION
**Pull request by n8henrie**
This branch was to help debug CI for https://github.com/quicksilver/Quicksilver/pull/2938#issuecomment-1694694593

### CODE REVIEW

**Comment by n8henrie** [comment]
I think this is ready for merge. It uploads a debug executable along with the release artifacts, which should hopefully empower end users to help us debug issues.

**Comment by n8henrie** [comment]
I've also updated the CI dependencies in this PR, which silences several annoying warnings.

**Comment by pjrobertson** [comment]
I see Quicksilver-debug here :) https://github.com/quicksilver/Quicksilver/actions/runs/6007687787

Can it be given an extension in the name. Is it a .zip or .dmg?

**Comment by pjrobertson** [comment]
@n8henrie  - waiting on this change (Adding an extension) then I'll push a new release out :)

**Comment by n8henrie** [comment]
@pjrobertson -- I actually removed the `.zip` extension due to: https://github.com/actions/upload-artifact#zipped-artifact-downloads:

> There is currently no way to download artifacts after a workflow run finishes in a format other than a zip or to download artifact contents individually. One of the consequences of this limitation is that if a zip is uploaded during a workflow run and then downloaded from the UI, there will be a double zip created.

So I had originally made it so that one saw `foo.zip` in the web interface, but once downloaded it showed as `foo.zip.zip` which I thought seemed uglier than having `foo` in the web interace and `foo.zip` once downloaded. I still think the latter is less ugly, but if you think it's more important to show the `.zip` in the web interface I'm happy to revert that.

**Comment by pjrobertson** [comment]
Makes sense. I see that when I download it it is correctly named Quicksilver-debug.zip, so I think this change is fine.

Merging :)

**Pull request merged**
